### ISSUE TITLE
code completion

### ISSUE THREAD

**Issue by gggerdy** [fdebrus/NeopoolHomeAssistant#1]
Hi,

Could you upload your full code please?

I'm missing the "accessoires" in the configuration.yaml and dashboard code?
Pool lights and shutter code is missing

Kind regards, 
G.

**Comment by fdebrus** [comment]
I should cleanup the "dashboard" as time allow :)

- **Shutter** this one is linked to a Somfy electric shutter. I've just centralized everything related to the pool in the same dashboard. just delete the shutter section. That should not be relevant to you.

- **Pool Light** please find the code in the configuration file, here is the relevant section.
  
unique_id: "pool_lights"
name: "Pool Lights"
device_class: switch
command_topic: "cmnd/SmartPool/NPLight"
state_topic: "stat/SmartPool/NPLIGHT"
value_template: >- 
{% set values = { 'OFF':'0', 'ON':'1' } %}
{{ values[value_json["NPLight"]] if value_json["NPLight"] in values.keys() else '99' }}
payload_on: "1"
payload_off: "0"


might you still have issue, please post the error you are getting so we can investigate further.

**Comment by gggerdy** [comment]
great thanks!

**Comment by fdebrus** [comment]
Shutter is not linked to aquarite aka sugarvalley aka oxilife but somfy
