### ISSUE TITLE
Question about dashboard regarding the light switch

### ISSUE THREAD

**Issue by JHurk** [fdebrus/NeopoolHomeAssistant#3]
Got the dashboard to work and after enabling the SetOption19 in Tasmota the entities became visible in HA.

One question;
I connected the pool lights to my Sugar Valley and I can control them with the switch on the dashboard.
But how do I get the switch to show the current state, just like a normal switch or light bulb in HA?
I know I can add it a a separate sensor to the dashboard, I did this for the Acid pump.
But would like it to show up like a normal light in HA.

<img width="1524" alt="Schermafbeelding 2023-10-20 om 12 35 18" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/e9f763b8-8670-4dec-af52-35d400a08992">

I tried making it a different device (from switch to light), it still functions but the state is also not visible.
For extra info; I did not add a gui switch in Tasmota for the light (maybe I need to do that so it will transfer this to HA via MQTT??)

**Comment by fdebrus** [comment]
I have the same since HA upgrade, I've not yet figured out how to fix it. As I switched off the pool, will be complex to troubleshoot before post winter. It might be a general question to be asked in HA forum as it's related to how MQTT switches behave since last HA release. Will further investigate on the forum and revert if any findings

**Comment by JHurk** [comment]
Understood, if I can do anything to test, please let me know.
I still have my pool operational for a week, max. two.
So I can do some testing if you like, with different settings or yaml.

**Comment by fdebrus** [comment]
- unique_id: "pool_lights"
      name: "MQTT Pool Lights"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPLight"
      state_topic: "stat/SmartPool/NPLIGHT"
      value_template: >- 
        {% set values = { 'OFF':'0', 'ON':'1' } %}
        {{ values[value_json["NPLight"]] if value_json["NPLight"] in values.keys() else '99' }}
      payload_on: "1"
      payload_off: "0"

using tool like MQTT explorer, could you check you get a topic value in  "stat/SmartPool/NPLIGHT" ?

**Comment by JHurk** [comment]
Not sure if I am doing this right, but I tried some of these things with the explorer in HA.
<img width="876" alt="Scherm­afbeelding 2023-10-20 om 14 02 29" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/e2965a31-3fed-4991-a198-6fd8eb35789c">

This does not give a result on screen

**Comment by JHurk** [comment]
Sorry, deleted my previous answer because it got a little complex.
1. When I publish the following command, I get no result in HA explorer
<img width="876" alt="Scherm­afbeelding 2023-10-20 om 14 02 29" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/609ef782-bd5e-4927-93bf-b4ba09bce259">

2. But after a few minutes I do get an answer, probably because the automation SmartPool_Sensors_Updated got triggered.
<img width="557" alt="Scherm­afbeelding 2023-10-20 om 14 05 25" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/4b51383a-e723-4d8a-9880-097d59d8b596">

**Comment by fdebrus** [comment]
same here, status of the MQTT switch remains "unknown" even after posting to stat/SmartPool/NPLIGHT

![image](https://github.com/fdebrus/NeopoolHomeAssistant/assets/33791533/2e988c59-7ae4-455b-9ffa-b158965bc11a)

**Comment by JHurk** [comment]
Same her, both for the lights and the pump switch.
So something with the yaml? Or maybe the Tasmota doesn't publish the expected state?
<img width="866" alt="Scherm­afbeelding 2023-10-20 om 14 09 38" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/da6cc778-c151-4b6b-aa88-52aaf77d4f0f">

**Comment by fdebrus** [comment]
it worked all fine for me before the latest HA upgrade, might be something has changed in the release. 

So I woul not touch yaml nor tasmota. It's a new HA behavior that we need to figure out

**Comment by JHurk** [comment]
The only thing in the release notes that comes close to MQTT or this issue is;
https://github.com/home-assistant/core/pull/101670
As far as I can tell, but my knowledge is not that extensive regarding bug fixing and coding.

**Comment by fdebrus** [comment]
got this working

mqtt:
  switch:
    - unique_id: "mySwitch"
      name: "my Switch"
      device_class: switch
      state_topic: "state/mySwitch"
      command_topic: "cmnd/mySwitch"

if I send OFF or ON to state/mySwitch, the dashboard item is updated accordingly. troubleshooting...

**Comment by JHurk** [comment]
Don't know if this is helping, seeing you already found some things during testing.
But looked at the previous release notes of September and found the following changes/fixes that might be related;

September 8 release https://github.com/home-assistant/core/pull/99943
September 12 release https://github.com/home-assistant/core/pull/100168 (Tasmota related change/fix)
September 24 release https://github.com/home-assistant/core/pull/100707 (MQTT state related)

**Comment by fdebrus** [comment]
try this

    - unique_id: "pool_lights"
      name: "Pool Lights"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPLight"
      state_topic: "stat/SmartPool/NPLIGHT"
      value_template: >- 
        {% set values = { 'OFF':'0', 'ON':'1' } %}
        {{ values[value_json["NPLight"]] if value_json["NPLight"] in values.keys() else '99' }}

so without 

      payload_on: "1"
      payload_off: "0"

**Comment by JHurk** [comment]
Nope, this doesn't change anything.
The buttons work (On makes the gui in Tasmota change the lights to On), but the state is not visible in the dashboard.
And via the developers tool --> status is still unknow
The strange thing is that the last updated time is somewhere around 13:04, while I just changed the status via de the switch button on the dashboard, around 14:35.
<img width="1087" alt="Scherm­afbeelding 2023-10-20 om 14 41 52" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/9d71bda6-db35-4fc7-8cb8-ee4e3b4b26f3">

**Comment by fdebrus** [comment]
You need to send 0 or 1 to  command_topic: "cmnd/SmartPool/NPLight"

![image](https://github.com/fdebrus/NeopoolHomeAssistant/assets/33791533/2f4b55b6-9097-4df3-88b4-4a69de8032d0)

next Tasmota module will answer with ON or OFF on state_topic: "stat/SmartPool/NPLIGHT"

Somehow, when I combine value_template and payload_on payload_off. the state of the swith is no longer updated.

**Comment by JHurk** [comment]
Does this help?
<img width="756" alt="Scherm­afbeelding 2023-10-20 om 14 56 37" src="https://github.com/fdebrus/NeopoolHomeAssistant/assets/7835370/bcf1d8cf-38a4-45e3-8c98-b84871b3da4c">

**Comment by fdebrus** [comment]
Damned, coffee helped :) go to your tasmota console and enter the following command

setoption4 1

**Comment by JHurk** [comment]
That's it!!! The switch turned into a on/off switch instantly and shows the status.
Thanks for this!

**Comment by fdebrus** [comment]
you're welcome. it's will also resolve the pump switch status

**Comment by JHurk** [comment]
Thanks again, and to confirm; the pump switch is also working now!
