### ISSUE TITLE
Not an issue but question - Hydrolysis slider function? 

### ISSUE THREAD

**Issue by JHurk** [fdebrus/NeopoolHomeAssistant#5]
What is de main purpose of the hydrolysis slider?
The value is between 0 and 30 with initial of 10.
I guess this is a way of setting the hydrolysis percentage (NPHydrolysis in Tasmota).
Correct or not? Because then why is the min 0 and max 30?
Shouldn't this be min 0 and max 100 (as in percent)?

I am confused and do not know if my assumption is correct or that I am missing something.
Thanks for you advice.

From configuration.yaml:
  
set_smartpool_hydrolysis:
    name: Hydrolysis
    initial: 10
    min: 0
    max: 30
    step: 1
    mode: slider

From helper_automation

alias: SmartPool_Helper_Hydrolysis_Set
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.set_smartpool_hydrolysis
condition: []
action:
  - service: mqtt.publish
    data:
      topic: cmnd/SmartPool/NPHydrolysis
      payload_template: "{{ states('input_number.set_smartpool_hydrolysis') }}"
mode: single

**Comment by fdebrus** [comment]
For my system, it set the Hydrolysis level in gr/hr. default being 10 gram by hour.

**Comment by JHurk** [comment]
Thanks, changed it and now it works. Just wanted to be sure before I changed something.
